CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE aspnetroles (
    id text NOT NULL,
    name character varying(256),
    normalizedname character varying(256),
    concurrencystamp text,
    CONSTRAINT "PK_aspnetroles" PRIMARY KEY (id)
);

CREATE TABLE aspnetusers (
    id text NOT NULL,
    username character varying(256),
    normalizedusername character varying(256),
    email character varying(256),
    normalizedemail character varying(256),
    emailconfirmed boolean NOT NULL,
    passwordhash text,
    securitystamp text,
    concurrencystamp text,
    phonenumber text,
    phonenumberconfirmed boolean NOT NULL,
    twofactorenabled boolean NOT NULL,
    lockoutend timestamp with time zone,
    lockoutenabled boolean NOT NULL,
    accessfailedcount integer NOT NULL,
    CONSTRAINT "PK_aspnetusers" PRIMARY KEY (id)
);

CREATE TABLE aspnetroleclaims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    roleid text NOT NULL,
    claimtype text,
    claimvalue text,
    CONSTRAINT "PK_aspnetroleclaims" PRIMARY KEY (id),
    CONSTRAINT "FK_aspnetroleclaims_aspnetroles_roleid" FOREIGN KEY (roleid) REFERENCES aspnetroles (id) ON DELETE CASCADE
);

CREATE TABLE aspnetuserclaims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    userid text NOT NULL,
    claimtype text,
    claimvalue text,
    CONSTRAINT "PK_aspnetuserclaims" PRIMARY KEY (id),
    CONSTRAINT "FK_aspnetuserclaims_aspnetusers_userid" FOREIGN KEY (userid) REFERENCES aspnetusers (id) ON DELETE CASCADE
);

CREATE TABLE aspnetuserlogins (
    loginprovider text NOT NULL,
    providerkey text NOT NULL,
    providerdisplayname text,
    userid text NOT NULL,
    CONSTRAINT "PK_aspnetuserlogins" PRIMARY KEY (loginprovider, providerkey),
    CONSTRAINT "FK_aspnetuserlogins_aspnetusers_userid" FOREIGN KEY (userid) REFERENCES aspnetusers (id) ON DELETE CASCADE
);

CREATE TABLE aspnetuserroles (
    userid text NOT NULL,
    roleid text NOT NULL,
    CONSTRAINT "PK_aspnetuserroles" PRIMARY KEY (userid, roleid),
    CONSTRAINT "FK_aspnetuserroles_aspnetroles_roleid" FOREIGN KEY (roleid) REFERENCES aspnetroles (id) ON DELETE CASCADE,
    CONSTRAINT "FK_aspnetuserroles_aspnetusers_userid" FOREIGN KEY (userid) REFERENCES aspnetusers (id) ON DELETE CASCADE
);

CREATE TABLE aspnetusertokens (
    userid text NOT NULL,
    loginprovider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_aspnetusertokens" PRIMARY KEY (userid, loginprovider, name),
    CONSTRAINT "FK_aspnetusertokens_aspnetusers_userid" FOREIGN KEY (userid) REFERENCES aspnetusers (id) ON DELETE CASCADE
);

CREATE INDEX "IX_aspnetroleclaims_roleid" ON aspnetroleclaims (roleid);

CREATE UNIQUE INDEX "RoleNameIndex" ON aspnetroles (normalizedname);

CREATE INDEX "IX_aspnetuserclaims_userid" ON aspnetuserclaims (userid);

CREATE INDEX "IX_aspnetuserlogins_userid" ON aspnetuserlogins (userid);

CREATE INDEX "IX_aspnetuserroles_roleid" ON aspnetuserroles (roleid);

CREATE INDEX "EmailIndex" ON aspnetusers (normalizedemail);

CREATE UNIQUE INDEX "UserNameIndex" ON aspnetusers (normalizedusername);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260827124944_InitialCreate', '10.0.11');

COMMIT;

